name: Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./examples/react build:ci
      - run: pnpm --filter ./examples/react exec next export
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./examples/react/out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
